SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


DROP DATABASE IF EXISTS cb;
CREATE DATABASE IF NOT EXISTS cb;
USE cb;


CREATE TABLE `CHATS`(
    `ID` INT PRIMARY KEY AUTO_INCREMENT,
    `USERNAME` VARCHAR(100),
    `CHATBOT` VARCHAR(100),
    `DATE` DATE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `login` (
  `username` VARCHAR(50) PRIMARY KEY,
  `email` VARCHAR(100),
  `password` VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `QUESTIONS` (
    `ID` INT PRIMARY KEY AUTO_INCREMENT,
    `QUESTION` VARCHAR(200),
    `ANSWER` VARCHAR(1000)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- INSERT INTO `QUESTIONS`(`ID`,`QUESTION`,`ANSWER`) VALUES()
-- COMMIT;